# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Package Builder 

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04, macos-10.15]
        java: [ '14' ]
        
    steps:
    - uses: actions/checkout@v2
      with:
        # Number of commits to fetch. 0 indicates all history.  
        fetch-depth: 1

    - name: Set up OpenJDK 
      uses: joschi/setup-jdk@v2
      with:
        java-version: ${{ matrix.java }}
        architecture: x64

    - name: Linux commands
      run: | 
        jpackage --help
      
    - name: Grant execute permissions
      run: |
        chmod +x gradlew
        chmod +x ./src/main/java/jpackage.jar

    - name: Run with Java 
      run: java -jar ./src/main/java/jpackage.jar 

    - name: Build with Gradle
      run: ./gradlew build 
