name: Package Builder 

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04, macos-10.15]
        java: [ '14' ]
        
    steps:
    - uses: actions/checkout@v2
      with:
        # Number of commits to fetch. 0 indicates all history.  
        fetch-depth: 1

    - name: Set up OpenJDK 
      uses: joschi/setup-jdk@v2
      with:
        java-version: ${{ matrix.java }}
        architecture: x64
      
    - name: Grant execute permissions
      run: |
        chmod +x gradlew

    - name: Package
      run: |
        ./gradlew build
        ./gradlew jpackage 
        
    - name: Check linux dir
      if: ${{matrix.os.ubuntu-18.04}}
      run: ls -al ./distribution
        
    - name: Check windows  dir
      if: ${{matrix.os.windows-2019}}
      run: dir /A ./distribution
       
    - name: Commit Packages
      uses: EndBug/add-and-commit@v4
      with:
        author_name: mitm001
        author_email: mitm001@users.noreply.github.com
        message: "Commit files for CI workflow"
        # Commits these files to root if and only if there are changes.
        add: "./distribution/*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}