name: Package Builder 

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04, macos-10.15]
        java: [ '14' ]
        
    steps:
    - uses: actions/checkout@v2
      with:
        # Number of commits to fetch. 0 indicates all history.  
        fetch-depth: 1
    
    #https://github.com/joschi/setup-jdk
    - name: Set up OpenJDK 
      uses: joschi/setup-jdk@v2
      with:
        java-version: ${{ matrix.java }}
        architecture: x64       
    
    - name: Patch apple finder timeout  
      if: matrix.os == 'macos-10.15'
      run: |
        JavaPath=$(which java)
        sqlite3 "$HOME/Library/Application Support/com.apple.TCC/TCC.db" "insert into access (service, client, client_type, allowed, prompt_count, indirect_object_identifier_type, indirect_object_identifier) values ('kTCCServiceAppleEvents', '$JavaPath', 1, 1, 1, 0, 'com.apple.finder')"

    - name: Grant execute permissions
      run: chmod +x gradlew

    - name: Package    
      run: ./gradlew packit 

    # Deploy a new release. Destination is declared in build.gradle by '--dest'.
    # see: https://github.com/marvinpinto/action-automatic-releases for param
    # options.
    - name: Upload release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ matrix.os }}
        prerelease: false
        title: "Development Build"
        files: | 
          ./build/jpackage/*.rpm
          ./build/jpackage/*.deb
          ./build/jpackage/*.msi
          ./build/jpackage/*.dmg
          ./build/jpackage/*.pkg
            
    - name: List build win
      if: matrix.os == 'windows-2019'
      run: dir /A .\\build\\jpackage
      shell: cmd
    
    - name: List build linux/mac
      if: matrix.os == 'ubuntu-18.04' || matrix.os == 'macos-10.15'
      run: ls -al ./build/jpackage
      shell: sh

    - name: Look for libjvm.so
      if: matrix.os == 'ubuntu-18.04'
      run: ls -al "${{ env.JAVA_HOME }}/lib/server"
      shell: sh