name: Package Builder 

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04, macos-10.15]
        java: [ '14' ]
        
    steps:
    - uses: actions/checkout@v2
      with:
        # Number of commits to fetch. 0 indicates all history.  
        fetch-depth: 1

    - name: Set up OpenJDK 
      uses: joschi/setup-jdk@v2
      with:
        java-version: ${{ matrix.java }}
        architecture: x64
      
    - name: Grant execute permissions
      run: chmod +x gradlew

    - name: Package
      run: ./gradlew jpackage 

    # Deploy a new release.
    # see: https://github.com/marvinpinto/action-automatic-releases for param
    # options.
    - name: Upload Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{matrix.os}}
        prerelease: false
        title: "Development Build"
        files: | 
          ./build/distribution/*.rpm
          ./build/distribution/*.deb
          ./build/distribution/*.msi
          ./build/distribution/*.dmg
          ./build/distribution/*.pkg
            
    - if: matrix.os == 'windows-2019'
      run: dir /A .\\build\\distribution
      shell: cmd
     
    - if: matrix.os == 'ubuntu-18.04' || matrix.os == 'macos-10.15'
      run: ls -al ./build/distribution
      shell: sh
